version: "3.8"

services:
    mariadb_init:
        environment:
            - AUR_CONFIG_IMMUTABLE=1

    git:
        environment:
            - AUR_CONFIG=/aurweb/conf/config
            - SSH_CMDLINE=${SSH_CMDLINE:-ssh ssh://aur@localhost:2222}
            - AUR_CONFIG_IMMUTABLE=1
            - GENERATE_SSH_KEYS=0
        ports:
            - "22:2222"
        volumes:
            - /etc/ssh/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
            - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
            - /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
            - ./conf:/aurweb/conf
            - ./data/git_data:/aurweb/aur.git
            - ./cache:/cache
            - mariadb_run:/var/run/mysqld

    php-fpm:
        environment:
            - AUR_CONFIG=/aurweb/conf/config
            - AURWEB_PHP_PREFIX=${AURWEB_PHP_PREFIX}
            - AURWEB_SSHD_PREFIX=${AURWEB_SSHD_PREFIX}
            - AUR_CONFIG_IMMUTABLE=1

    fastapi:
        environment:
            - AUR_CONFIG=conf/config
            - FASTAPI_BACKEND=${FASTAPI_BACKEND}
            - FASTAPI_WORKERS=${FASTAPI_WORKERS}
            - AURWEB_FASTAPI_PREFIX=${AURWEB_FASTAPI_PREFIX}
            - AURWEB_SSHD_PREFIX=${AURWEB_SSHD_PREFIX}
            - PROMETHEUS_MULTIPROC_DIR=/tmp_prometheus
            - AUR_CONFIG_IMMUTABLE=1

    cron:
        environment:
            AUR_CONFIG=conf/config
            AUR_CONFIG_IMMUTABLE=1
