version: "3.8"

services:
  mariadb_init:
    depends_on:
      mariadb:
        condition: service_healthy

  ca:
    volumes:
      - ./cache:/cache

  git:
    volumes:
      - ./data/git_data:/aurweb/aur.git
  
      - ./cache:/cache

  smartgit:
    volumes:
      - ./data/git_data:/aurweb/aur.git
      
      - ./cache:/cache
      - smartgit_run:/var/run/smartgit
    depends_on:
      mariadb:
        condition: service_healthy

  php-fpm:
    volumes:
      - ./cache:/cache
      - ./conf:/aurweb/conf
      - ./aurweb:/aurweb/aurweb
      - ./migrations:/aurweb/migrations
      - ./test:/aurweb/test
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib
      - ./templates:/aurweb/templates

  fastapi:
    volumes:
      - ./cache:/cache
      - ./conf:/aurweb/conf
      - ./aurweb:/aurweb/aurweb
      - ./migrations:/aurweb/migrations
      - ./test:/aurweb/test
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib
      - ./templates:/aurweb/templates

  nginx:
    volumes:
      - ./data/git_data:/aurweb/aur.git
      
      - ./cache:/cache
      - ./logs:/var/log/nginx
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib

